# Generated by Django 3.2.12 on 2023-03-01 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djstripe', '0007_2_4'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='business_type',
            field=models.CharField(
                blank=True,
                default="",
                help_text="The business type.",
                max_length=255,
                null=True,
            ),
        ),
    ]
